spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none&moveFailed=error
toRoute1: file:data/output
toRoute2: jdbc:dataSource
toRoute3: file:data/output?fileName=Success.txt

message: DEV environment

---

spring:
  profiles: mock

startRoute: direct:input
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: mock:output

message: MOCK environment

---

spring:
  profiles: stage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource

message: STAGE environment

---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource

message: PROD environment

---